//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SLCfAbstractGiveRedPacketMessageContent.h"

//#import "SLCfGiveRedPacketMessageContent-Protocol.h"

@class NSString, SLCfRedPacketType;

@interface SLCfGiveRedPacketMessageContentImpl : SLCfAbstractGiveRedPacketMessageContent //<SLCfGiveRedPacketMessageContent>
{
    SLCfRedPacketType *type_;
    NSString *text_;
    double amount_;
    NSString *tradeNumber_;
    _Bool collected_;
}

//+ (const struct J2ObjcClassInfo *)__metadata;
- (double)getAmount;
- (id)getRedPacketType;
- (id)getText;
- (id)getTradeNumber;
- (id)initWithSLCfRedPacketType:(id)arg1 withNSString:(id)arg2 withDouble:(double)arg3 withNSString:(id)arg4 withBoolean:(_Bool)arg5;
- (_Bool)isCollected;
- (void)setCollectedWithBoolean:(_Bool)arg1;


@end

