//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;
@protocol SLCtMessage;

@interface SLChatMessageViewModel : NSObject
{
    id <SLCtMessage> message_;
    int displayedTime_;
    int readCount_;
    _Bool isSelected_;
    _Bool isPreviewed_;
    _Bool dirty_;
    NSString *formatTimeString_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
- (id)getAlternativeMessage;
- (id)getContent;
- (long long)getCursor;
- (int)getDisplayedTime;
- (id)getFormatTimeString;
- (_Bool)getIsPreviewed;
- (id)getMessage;
- (_Bool)getMessageCanBeBurned;
- (id)getOriginalSender;
- (int)getReadCount;
- (int)getSelfDestructTime;
- (id)getSenderAvatar;
- (id)getSenderDisplayName;
- (long long)getSenderId;
- (id)getSenderUserType;
- (id)getStatus;
- (long long)getTimestamp;
- (id)getUuid;
- (id)initWithSLCtMessage:(id)arg1;
- (_Bool)isDirty;
- (_Bool)isFromMyself;
- (_Bool)isScreenShotSystemMessage;
- (_Bool)isSelected;
- (_Bool)isSystemSelfDestructDisableMessage;
- (_Bool)isSystemSelfDestructEnableMessage;
- (void)setContentWithSLMessageContent:(id)arg1;
- (void)setDirtyWithBoolean:(_Bool)arg1;
- (void)setDisplayedTimeWithInt:(int)arg1;
- (void)setFormatTimeStringWithNSString:(id)arg1;
- (void)setIsPreviewedWithBoolean:(_Bool)arg1;
- (void)setIsSelectedWithBoolean:(_Bool)arg1;
- (void)setReadCountWithInt:(int)arg1;
- (void)setStatusWithSLCrMessage_Status:(id)arg1;

@end

